version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: spark-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BEmbzFjwu8
      POSTGRES_DB: spark
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: /bin/sh -c "npx prisma migrate dev && npx prisma generate && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata:
